# azure-pipelines.yml
trigger:
- develop
- release
- master

pool:
  name: Default
  demands:
  - agent.name -equals self-hosted

resources:
  repositories:
    - repository: templates
      type: git
      name: cloud-devops-evaluacion
      ref: 'master'

stages:
- template: templates/buildTemplate.yml@templates