# azure-pipelines.yml
trigger:
- develop
- release
- master

# pooml:
#   vmIage: 'ubuntu-latest'

resources:
  repositories:
    - repository: templates
      type: git
      name: cloud-devops-evaluacion
      ref: 'master'

stages:
- template: templates/buildTemplate.yml@templates