# azure-pipelines.yml
parameters:
- name: AWS_ACCOUNT
  type: string
  default: 'AWS_ACCOUNT'
- name: REGION_ACCOUNT
  type: string
  default: 'us-east-1'

trigger:
- develop
- release
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: templates
      type: git
      name: cloud-devops-evaluacion
      ref: 'master'

stages:
- template: Build
  parameters:
    AWS_ACCOUNT: '${{ parameters.AWS_ACCOUNT }}'
    REGION_ACCOUNT: '${{ parameters.REGION_ACCOUNT }}'